### ISSUE TITLE
Database password error

### ISSUE THREAD

**Issue by ezforhamza** [rid17pawar/HospitalManagement#18]
Hello and Aaslam u Alikum, Mam I need a little help in setting up the Hospital management System project you made. Everything is fine I just need to know where do I need to insert my database password to establish connection with MySQL. I get password error when I click on login.

**Comment by rid17pawar** [comment]
In the below file: 
https://github.com/rid17pawar/HospitalManagement/blob/master/src/main/webapp/WEB-INF/springMVC-servlet.xml at line 47
